### ISSUE TITLE
popt.h not available in Windows

### ISSUE THREAD

**Issue by chaowu2009** [sourishg/stereo-calibration#1]
any thought to removed that dependency?

Thanks.

**Comment by sourishg** [comment]
Hi @chaowu2009 - I didn't really keep Windows in mind while making this tool. I used popt to parse command line arguments. You can either remove that dependency and change values manually within the code or you could simply try something like this: https://msdn.microsoft.com/en-us/library/17w5ykft.aspx

**Comment by tyhenry** [comment]
just made a fork for windows that uses ccxopts.hpp instead of popt lib
https://github.com/tyhenry/stereo-calibration

**Comment by sourishg** [comment]
@tyhenry thank you so much for working on this! If it's compiling and working on both platforms please open a PR. I'll merge.
